spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://localhost:3306/github-developer-skills
    username: user
    password: password

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR