spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:mysql://localhost:3306/github-developer-skills
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: ERROR
    org.springframework: ERROR
