version: '3.3'
services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'github-developer-skills'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'